name: auto_subimt

on:
  #push:
    #branches: [ master ]
 # pull_request:
 #  branches: [ master ]
  schedule:
    - cron: 0 1 1 DEC *
 # watch:
 #   types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        python3 rw.py 
        
    - name: commit
      run: |
        git config --global user.email 1233@qq.com
        git config --global user.name wsw
        git add .
        git commit -m "update" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
